FROM fasteiner/ubuntu-20.04-mpich:latest

# Set default value for USERNAME, which can be overridden during build
ARG USERNAME=aprg

# Switch to the new user
USER ${USERNAME}

# Set the default command to bash (optional)
CMD ["/bin/bash"]